services:
  - type: web
    name: my-node-app
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true